// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbbppnrotybgpbkkmina.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYnBwbnJvdHliZ3Bia2ttaW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTg4NDEsImV4cCI6MjA2NjE5NDg0MX0.wcU2rAtMlYRgjwQIjBZTOKZejTyVMCKcafeHGB6NP_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);